# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pregunta_pb2 as pregunta__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pregunta_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PreguntaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerPreguntaCompleta = channel.unary_unary(
                '/bancopreguntas.PreguntaService/ObtenerPreguntaCompleta',
                request_serializer=pregunta__pb2.ObtenerPreguntaRequest.SerializeToString,
                response_deserializer=pregunta__pb2.PreguntaCompletaResponse.FromString,
                _registered_method=True)


class PreguntaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObtenerPreguntaCompleta(self, request, context):
        """Devuelve el detalle completo de una pregunta para que
        Ciclo de Vida y Revisión pueda evaluarla (CU-07).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreguntaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerPreguntaCompleta': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerPreguntaCompleta,
                    request_deserializer=pregunta__pb2.ObtenerPreguntaRequest.FromString,
                    response_serializer=pregunta__pb2.PreguntaCompletaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bancopreguntas.PreguntaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bancopreguntas.PreguntaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreguntaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObtenerPreguntaCompleta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bancopreguntas.PreguntaService/ObtenerPreguntaCompleta',
            pregunta__pb2.ObtenerPreguntaRequest.SerializeToString,
            pregunta__pb2.PreguntaCompletaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
